"""Moodle Web Services token + disconnect-reason columns on user.

Revision ID: 043
Revises: 042
Create Date: 2026-05-01

Powers automatic Moodle assignment-submission detection (Phase B
2026-05-01 — operator request: "I wanted the submitted status to be
automatically caught, I feel like we keep asking the user for too
much input").

Schema additions on `user`:
  - moodle_ws_token: 32-char Moodle Web Services token, generated by
    the user from Moodle Preferences → Security keys. Plaintext per
    existing convention (matches moodle_ics_url + google_refresh_token
    trust class). NEVER returned in any API response, NEVER logged.
    Fernet encryption deferred to Phase 6+ security debt batch.
  - moodle_ws_last_synced_at: stamp of last successful submissions
    sync. Surfaces in Settings so the user can see freshness.
  - moodle_ws_disconnect_reason: set when sync fails permanently
    (e.g., 'invalidtoken' from Moodle 4xx → token rotated). Frontend
    surfaces "Reconnect Web Services" prompt when non-null. Cleared
    on successful reconnect.

Why a separate column from moodle_ics_url + moodle_disconnect_reason:
  iCal feed and Web Services are independent capabilities. iCal only
  needs the URL+authtoken (read-only calendar). Web Services needs a
  separate user-generated token (read/write across many APIs). User
  may have one without the other (e.g., iCal connected but never
  generated WS token). Schema treats them as orthogonal.

Companion: archive/migration_043_for_supabase_sql_editor.sql for the
operator's pre-pull Supabase paste (per feedback_migration_first.md).
"""
from alembic import op
import sqlalchemy as sa


revision = "043"
down_revision = "042"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "user",
        sa.Column("moodle_ws_token", sa.Text(), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("moodle_ws_last_synced_at", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("moodle_ws_disconnect_reason", sa.String(64), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("user", "moodle_ws_disconnect_reason")
    op.drop_column("user", "moodle_ws_last_synced_at")
    op.drop_column("user", "moodle_ws_token")
