"""Pydantic schemas for the onboarding brain-dump multi-item parser.

Used by POST /v1/brain-dump/parse (preview) and POST /v1/brain-dump/commit
(write-through). Heuristic-only fan-out per operator decision 2026-04-28:
no model dependency on the synchronous critical path. Deterministic deadline
suggestions remain non-canonical until the user confirms one.
"""
from datetime import datetime
from typing import Literal, Optional
from pydantic import BaseModel, Field


ItemKind = Literal["task", "deadline"]
BindingTier = Literal["tier1_auto", "tier2_ask", "tier3_skip"]
BindingTargetKind = Literal["parsed_deadline", "existing_deadline"]
ParserStatus = Literal["heuristic_parsed", "empty"]
CommitOutcomeStatus = Literal["created", "reused", "rejected", "failed"]


class BrainDumpParsedItem(BaseModel):
    """One parsed entry from the user's free-text dump."""
    item_id: str
    kind: ItemKind
    title: str
    description: Optional[str] = None
    # ISO datetime in user's local TZ.
    # For tasks: planned_start_local (default now+30min when no anchor parsed).
    # For deadlines: due_at_local (required for deadline kind).
    when_local: Optional[datetime] = None
    duration_minutes: Optional[int] = None
    # Auto-inferred taxonomy used for preview + commit. Low-authority:
    # user can still edit after creation, and TaskManager re-checks if absent.
    category: Optional[str] = None
    category_source: Optional[str] = None
    # Duration provenance so prior-filled durations are not mistaken for
    # explicit user intent.
    duration_source: Optional[str] = None
    duration_confidence: Optional[float] = None
    duration_basis: Optional[str] = None
    # Heuristic confidence in this item being correctly typed.
    # High (≥0.85): explicit deadline keyword + date, or unambiguous task
    # Medium (0.45-0.85): one signal, ambiguous typing
    # Low (<0.45): brittle — surface for user edit
    confidence: float = 1.0


class BrainDumpBindingSuggestion(BaseModel):
    """Suggested link between a parsed task and a bindable obligation.

    Backward-compatible fields (`deadline_item_id`, `deadline_title`) are
    preserved for same-dump bindings. Wave 1 adds `existing_deadline`
    targets so Pulse can bind newly parsed tasks to obligations that already
    exist in the user's account without inventing duplicate deadline rows.
    """
    binding_id: str
    task_item_id: str
    deadline_item_id: str
    deadline_title: str
    confidence: float
    tier: BindingTier
    source: str  # deadline heuristic source label
    target_kind: BindingTargetKind = "parsed_deadline"
    # Present when target_kind == existing_deadline.
    deadline_id: Optional[str] = None
    target_due_at: Optional[datetime] = None
    target_state: Optional[str] = None
    target_origin: Optional[str] = None


class BrainDumpParseRequest(BaseModel):
    raw_text: str = Field(..., min_length=1, max_length=8000)
    current_local_iso: Optional[str] = None


class BrainDumpParseResponse(BaseModel):
    items: list[BrainDumpParsedItem]
    bindings: list[BrainDumpBindingSuggestion]
    parser_status: ParserStatus


class BrainDumpCommitItem(BaseModel):
    """User-confirmed item from the preview step."""
    item_id: str
    kind: ItemKind
    title: str = Field(..., min_length=1, max_length=255)
    description: Optional[str] = Field(None, max_length=2000)
    when_local: Optional[datetime] = None
    duration_minutes: Optional[int] = Field(None, ge=1, le=720)
    category: Optional[str] = Field(None, max_length=64)
    category_source: Optional[str] = Field(None, max_length=80)
    duration_source: Optional[str] = Field(None, max_length=80)
    duration_confidence: Optional[float] = None
    duration_basis: Optional[str] = Field(None, max_length=160)


class BrainDumpCommitBinding(BaseModel):
    """User-confirmed binding from the one-tap question block."""
    task_item_id: str
    # Same-dump target, generated by /parse from a parsed deadline item.
    deadline_item_id: Optional[str] = None
    # Existing account deadline target, surfaced by Wave 1 parse.
    deadline_id: Optional[str] = None
    target_kind: BindingTargetKind = "parsed_deadline"


class BrainDumpCommitRequest(BaseModel):
    items: list[BrainDumpCommitItem] = Field(..., min_length=0)
    bindings: list[BrainDumpCommitBinding] = Field(default_factory=list)


class BrainDumpFailedItem(BaseModel):
    """An item in the commit batch that couldn't be created.

    Surfaced in BrainDumpCommitResponse.failed_items so the frontend
    can render a retry-or-edit panel instead of silently dropping the
    user's input. LYR-114 fix 2026-04-30 — pre-fix the endpoint logged
    failures + returned 200 with no per-item failure surface, so the
    user thought 5 tasks committed when actually 2 did.
    """
    item_id: str
    kind: ItemKind
    title: str
    # Stable machine-readable reason code for branchable UX:
    #   - "past_time"      → start time was in the past (TaskManager 5-min guard)
    #   - "missing_when"   → deadline had no when_local
    #   - "deadline_terminal_state" → bound deadline already completed/missed
    #   - "deadline_not_found" → bound deadline_id didn't resolve
    #   - "validation"     → other ValueError
    #   - "internal"       → unexpected exception (catch-all; logged with exc_info)
    reason: str
    # Human-readable detail for tooltip / debug context
    detail: str
    # UX hint — what the frontend should offer as a one-click recovery
    # action. None when no obvious retry exists (e.g., internal errors).
    #   - "schedule_tomorrow_same_time"
    #   - "edit_when_local"
    #   - "remove_deadline_binding"
    #   - None
    retry_hint: Optional[str] = None


class BrainDumpCommitOutcome(BaseModel):
    """Per-item commit truth for an accepted Brain Dump preview."""

    item_id: str
    kind: ItemKind
    title: str
    status: CommitOutcomeStatus
    canonical_id: Optional[str] = None
    reason: Optional[str] = None
    detail: Optional[str] = None
    retry_hint: Optional[str] = None


class BrainDumpCommitResponse(BaseModel):
    tasks_created: int
    deadlines_created: int
    bindings_applied: int
    task_ids: list[str]
    deadline_ids: list[str]
    outcomes: list[BrainDumpCommitOutcome] = Field(default_factory=list)
    # LYR-114 fix 2026-04-30: per-item failure surface. Empty when all
    # items committed cleanly. Frontend renders a dismissible warning
    # panel listing failures + a retry affordance per item.
    failed_items: list[BrainDumpFailedItem] = Field(default_factory=list)
